name: CI/CD Backend - Tienda Perritos

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push imagen Backend
        run: |
          docker build -t tienda-backend .
          docker tag tienda-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

      - name: Desplegar en EC2 Backend
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest",
              "docker stop tienda-backend || true",
              "docker rm tienda-backend || true",
              "docker run -d --name tienda-backend -p 3001:3001 --env DB_HOST=localhost --env DB_USER=root --env DB_PASSWORD=admin123 --env DB_NAME=tienda_perritos ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"
            ]}' \
            --output text
